/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as EmployeeIndexImport } from './routes/employee/index'
import { Route as CafeIndexImport } from './routes/cafe/index'
import { Route as EmployeeInfoImport } from './routes/employee/info'
import { Route as CafeInfoImport } from './routes/cafe/info'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EmployeeIndexRoute = EmployeeIndexImport.update({
  path: '/employee/',
  getParentRoute: () => rootRoute,
} as any)

const CafeIndexRoute = CafeIndexImport.update({
  path: '/cafe/',
  getParentRoute: () => rootRoute,
} as any)

const EmployeeInfoRoute = EmployeeInfoImport.update({
  path: '/employee/info',
  getParentRoute: () => rootRoute,
} as any)

const CafeInfoRoute = CafeInfoImport.update({
  path: '/cafe/info',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cafe/info': {
      id: '/cafe/info'
      path: '/cafe/info'
      fullPath: '/cafe/info'
      preLoaderRoute: typeof CafeInfoImport
      parentRoute: typeof rootRoute
    }
    '/employee/info': {
      id: '/employee/info'
      path: '/employee/info'
      fullPath: '/employee/info'
      preLoaderRoute: typeof EmployeeInfoImport
      parentRoute: typeof rootRoute
    }
    '/cafe/': {
      id: '/cafe/'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeIndexImport
      parentRoute: typeof rootRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CafeInfoRoute,
  EmployeeInfoRoute,
  CafeIndexRoute,
  EmployeeIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cafe/info",
        "/employee/info",
        "/cafe/",
        "/employee/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cafe/info": {
      "filePath": "cafe/info.tsx"
    },
    "/employee/info": {
      "filePath": "employee/info.tsx"
    },
    "/cafe/": {
      "filePath": "cafe/index.tsx"
    },
    "/employee/": {
      "filePath": "employee/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
